const events = {
  INIT_APP: 'INIT_APP',
  APP_LOADED: 'APP_LOADED',
  AUTHENTICATE_USER: 'AUTHENTICATE_USER',
  UNAUTHENTICATE_USER: 'UNAUTHENTICATE_USER',
  GET_USER_PROFILE: 'GET_USER_PROFILE'
};

export default events;
